name: Build and Test OpenPDAC-13

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install OpenFOAM 13
      - name: Install OpenFOAM 13
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13
      
      # Step 3: Compile Solver and Utilities
      - name: Compile Solver and Utilities
        # Force this step to run using the bash shell
        shell: bash
        run: |
          # Source the OpenFOAM environment
          source /opt/openfoam13/etc/bashrc

          # Compile the OpenPDAC solver
          echo "Compiling OpenPDAC solver..."
          cd applications/OpenPDAC
          ./Allwmake
          
          # Compile the topoGrid utility
          echo "Compiling topoGrid utility..."
          cd ../../applications/utilities/topoGrid
          wmake

      # Step 4: Run the test cases
      - name: Run test cases
        # Force this step to run using the bash shell as well
        shell: bash
        run: |
          # Source the OpenFOAM environment
          source /opt/openfoam13/etc/bashrc
          
          # Navigate into the main test directory
          cd run
          
          # Make the master test script executable
          chmod +x ./run-all-tests.sh
          
          # Execute the test script
          ./run-all-tests.sh
