name: Build and Test OpenPDAC-13

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install OpenFOAM 13
      - name: Install OpenFOAM 13
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13

      # Step 3: Configure the Bash environment (Mimics the Dockerfile)
      - name: Configure Bash Environment
        run: |
          # Add the OpenFOAM source command to the user's .bashrc file.
          # This makes the environment persistent for interactive shells.
          echo "source /opt/openfoam13/etc/bashrc" >> /home/runner/.bashrc
          echo "Bash environment configured."

      # Step 4: Compile Solver and Utilities
      - name: Compile Solver and Utilities
        # Run commands in an INTERACTIVE bash shell (-i)
        # This forces it to read .bashrc first, loading the OpenFOAM environment.
        run: |
          bash -ic '
            echo "Compiling OpenPDAC solver..."
            cd applications/OpenPDAC
            ./Allwmake
            
            echo "Compiling topoGrid utility..."
            cd ../../applications/utilities/topoGrid
            wmake
          '

      # Step 5: Run the test cases
      - name: Run test cases
        # Run this in an interactive shell as well
        run: |
          bash -ic '
            cd run
            chmod +x ./run-all-tests.sh
            ./run-all-tests.sh
          '
