name: Build and Test OpenPDAC-13

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenFOAM 13
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13

      - name: Setup Conda and Create Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false 
          activate-environment: ""
          environment-file: environment.yml
          
      # Non modifichiamo più .bashrc. È troppo fragile.

      - name: Compile Solver and Utilities
        run: |
          bash -ic '
            set +m  # Sopprime le avvertenze del terminale

            # 1. Carica l''ambiente OpenFOAM
            source /opt/openfoam13/etc/bashrc

            # 2. Carica l''ambiente Conda (trovando il path di base di miniconda)
            source $(conda info --base)/etc/profile.d/conda.sh
            
            # 3. Attiva l''ambiente Python specifico
            conda activate OpenPDACconda
            
            # 4. Ora, procedi con la compilazione
            echo "Compiling OpenPDAC solver..."
            cd applications/OpenPDAC
            # ./Allwmake
            
            echo "Compiling topoGrid utility..."
            cd ../../applications/utilities/topoGrid
            wmake
          '

      - name: Run the test cases
        run: |
          bash -ic '
            set +m # Sopprime le avvertenze del terminale

            # Ripeti la stessa sequenza di attivazione robusta
            source /opt/openfoam13/etc/bashrc
            source $(conda info --base)/etc/profile.d/conda.sh
            conda activate OpenPDACconda

            cd run
            chmod +x ./run-all-tests.sh
            ./run-all-tests.sh
          '
