name: Build and Test OpenPDAC-13

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13 wget
          
      - name: Install Miniconda and Create Environment Manually
        run: |
          # Scarica e installa Miniconda
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          
          # Inizializza Conda per la shell e crea l'ambiente
          source $HOME/miniconda/bin/activate
          conda init
          conda env create -f environment.yml

      - name: Compile Solver and Utilities
        run: |
          bash -ic '
            set +m
            
            # Il .bashrc è stato modificato da "conda init"
            # Quindi l''attivazione funzionerà
            conda activate OpenPDACconda
            
            # Ora carica OpenFOAM
            source /opt/openfoam13/etc/bashrc
            
            # Compila
            echo "Compiling OpenPDAC solver..."
            cd applications/OpenPDAC
            # ./Allwmake
            cd ../../applications/utilities/topoGrid
            wmake
          '

      - name: Run the test cases
        run: |
          bash -ic '
            set +m 
            conda activate OpenPDACconda
            source /opt/openfoam13/etc/bashrc
            
            cd run
            chmod +x ./run-all-tests.sh
            ./run-all-tests.sh
          '
