name: Build and Test OpenPDAC-13

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenFOAM 13
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13

      - name: Setup Conda and Create Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false 
          activate-environment: ""
          environment-file: environment.yml
          
      - name: Compile Solver and Utilities
        run: |
          bash -ic '
            set +m  # Suppress terminal warnings

            # --- START OF NEW ACTIVATION SEQUENCE ---

            # 1. Initialize Conda FIRST
            source $(conda info --base)/etc/profile.d/conda.sh
            
            # 2. (Diagnostic) Verify that the environment is visible
            echo "--- Available Conda Environments ---"
            conda info --envs
            echo "------------------------------------"
            
            # 3. Activate the Conda environment
            conda activate OpenPDACconda

            # 4. NOW, source the OpenFOAM environment on top of the active Conda env
            source /opt/openfoam13/etc/bashrc
            
            # --- END OF NEW ACTIVATION SEQUENCE ---
            
            # 5. Proceed with compilation
            echo "Compiling OpenPDAC solver..."
            cd applications/OpenPDAC
            # ./Allwmake
            
            echo "Compiling topoGrid utility..."
            cd ../../applications/utilities/topoGrid
            wmake
          '

      - name: Run the test cases
        run: |
          bash -ic '
            set +m 

            # Repeat the same robust activation sequence
            source $(conda info --base)/etc/profile.d/conda.sh
            conda activate OpenPDACconda
            source /opt/openfoam13/etc/bashrc

            # Proceed with tests
            cd run
            chmod +x ./run-all-tests.sh
            ./run-all-tests.sh
          '
