name: Build and Test OpenPDAC-13

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # NEW: Define the shell for all steps at the job level
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenFOAM 13
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13

      - name: Setup Conda and Install Dependencies from File
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Tell conda to create and activate the environment named in the file
          activate-environment: OpenPDACconda 
          environment-file: environment.yml
          # No need for auto-activate-base, it will be handled by the activation
          
      - name: Compile Solver and Utilities
        run: |
          # The Conda environment is already active from the previous step.
          # We just need to source OpenFOAM on top of it.
          source /opt/openfoam13/etc/bashrc
          
          # (Diagnostic) Verify both environments are loaded
          echo "--- Python Path ---"
          which python
          echo "--- Conda Env ---"
          conda info --envs
          echo "--- OpenFOAM Command Path ---"
          which blockMesh
          echo "---------------------"
          
          echo "Compiling OpenPDAC solver..."
          cd applications/OpenPDAC
          # ./Allwmake
          
          echo "Compiling topoGrid utility..."
          cd ../../applications/utilities/topoGrid
          wmake

      - name: Run the test cases
        run: |
          # Repeat the simple sourcing of OpenFOAM
          source /opt/openfoam13/etc/bashrc

          cd run
          chmod +x ./run-all-tests.sh
          ./run-all-tests.sh
