name: Build and Test OpenPDAC-13

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenFOAM 13
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13

      - name: Setup Conda and Create Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false 
          activate-environment: ""
          environment-file: environment.yml
          
      # We no longer need the 'Configure Bash Environment' step that modifies .bashrc

      - name: Compile Solver and Utilities
        # The shell is now specified at the job level for consistency
        shell: bash -el {0}
        run: |
          # Explicitly load the OpenFOAM environment first
          source /opt/openfoam13/etc/bashrc
          
          # Now, explicitly activate the conda environment.
          # The 'conda' command is available from the setup-miniconda step.
          conda activate OpenPDACconda
          
          # Proceed with compilation
          echo "Compiling OpenPDAC solver..."
          cd applications/OpenPDAC
          # ./Allwmake
          
          echo "Compiling topoGrid utility..."
          cd ../../applications/utilities/topoGrid
          wmake

      - name: Run the test cases
        shell: bash -el {0}
        run: |
          # Repeat the same robust activation sequence
          source /opt/openfoam13/etc/bashrc
          conda activate OpenPDACconda

          cd run
          chmod +x ./run-all-tests.sh
          ./run-all-tests.sh
